// export const BASE_URL = 'http://localhost:4000'
// export const BASE_URL = 'https://dru-backend.herokuapp.com'
export const BASE_URL = process.env.NEXT_PUBLIC_API_URL
export const BASE_CLIENT_URL = process.env.NEXT_PUBLIC_CLIENT_URL
export const GET = 'GET'
export const POST = 'POST'
export const PUT = 'PUT'
export const PATCH = 'PATCH'
export const DELETE = 'DELETE'
export const JSON_HEADER = { 'Content-type': 'application/json' }
export const FORM_HEADER = { 'Content-type': 'multipart/form-data' }
export const NETWORK_ERROR_MSG = '네트워크 에러가 발생하였습니다.'
