import * as React from 'react'
import { FooterContainer } from '../styles/Layout.styles'
import logo from '../assets/img/flogo.svg'
import github from '../assets/img/github.svg'
import blog from '../assets/img/blog.svg'
import insta from '../assets/img/insta.svg'

interface IFooterProps {}

export default function Footer(props: IFooterProps) {
  return (
    <FooterContainer>
      <div className="wrap">
        <div className="imgContainer">
          <img src={logo} alt="logo" />
        </div>
        <div className="descript">Contributor | 이성범 김지현</div>
        <div className="descript">Generated by | React.js, Node.js, MongoDB, Koa.js, Express.js</div>
        <div className="descript">Copyrightⓒ2021 What is Your Disease All rights reserved.</div>
        <div className="snsContainer">
          <div className="name">Info.이성범</div>
          <div className="snsIconContainer">
            <a href="" target="_blank">
              <img src={github} alt="github icon" />
            </a>
            <a href="" target="_blank">
              <img src={blog} alt="blog icon" />
            </a>
            <a href="" target="_blank">
              <img src={insta} alt="instagram icon" />
            </a>
          </div>
          <div className="name jihyun">Info.김지현</div>
          <div className="snsIconContainer">
            <a href="https://github.com/jkim68888" target="_blank">
              <img src={github} alt="github icon" />
            </a>
            <a href="https://jkim68888.github.io/" target="_blank">
              <img src={blog} alt="blog icon" />
            </a>
            <a href="https://www.instagram.com/hyunn383/" target="_blank">
              <img src={insta} alt="instagram icon" />
            </a>
          </div>
        </div>
      </div>
    </FooterContainer>
  )
}
