import * as React from 'react'
import { FooterContainer } from '../styles/Layout.styles'
import logo from '../assets/img/flogo.svg'
import github from '../assets/img/github.svg'
import insta from '../assets/img/insta.svg'

interface IFooterProps {}
interface IInfoCardProps {
  name: String
  githubName: String
  instaName: String
}

const InfoCard = ({ name, githubName, instaName }: IInfoCardProps) => (
  <div className="infoCardWrap">
    <div className="name">Info.{name}</div>
    <div className="snsIconContainer">
      <a
        href={`https://github.com/${githubName}`}
        target="_blank"
        rel="noreferrer"
      >
        <img src={github} alt="github icon" />
      </a>
      <a
        href={`https://www.instagram.com/${instaName}/`}
        target="_blank"
        rel="noreferrer"
      >
        <img src={insta} alt="instagram icon" />
      </a>
    </div>
  </div>
)

export default function Footer(props: IFooterProps) {
  return (
    <FooterContainer>
      <div className="wrap">
        <div className="imgContainer">
          <img src={logo} alt="logo" />
        </div>
        <div className="descript">Contributor | 이성범 김지현 박지후</div>
        <div className="descript">
          Generated by | React.js, Node.js, MongoDB, Koa.js, Express.js
        </div>
        <div className="descript">
          Copyrightⓒ2021 What is Your Disease All rights reserved.
        </div>
        <div className="snsContainer">
          <InfoCard
            name="이성범"
            githubName="SeongBeom27"
            instaName="seong_bm"
          />
          <InfoCard name="김지현" githubName="jkim68888" instaName="hyunn383" />
          <InfoCard name="박지후" githubName="jeehoo0767" instaName="wln__n" />
        </div>
      </div>
    </FooterContainer>
  )
}
